### ISSUE TITLE
Wealth of Nations style Time play

### ISSUE THREAD

**Issue by bbengfort** [bbengfort/jobs-report#34]
http://bost.ocks.org/mike/nations/

**Comment by asmagen** [comment]
Working on that...

**Comment by bbengfort** [comment]
@asmagen: I got the app to work -- now we just have to select which four dimensions we want to display for our particular data. 

Right now I have added regions according to the [Bureau of Economic Analysis regions](http://en.wikipedia.org/wiki/List_of_regions_of_the_United_States#Bureau_of_Economic_Analysis_regions) - this will be the color dimension. 

Format for the data is as follows:

```json
[
    {
        "name": "name of state",
        "region": "name of region", 
        "dimX": [
            [period, value],
        ],
       "dimY": [
            [period, value],
        ],
        "dimR": [
            [period, value],
        ],
    }
]
```

Where dimX is the x value, dimY is the y value and dimR is the radius of the circle.
